services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432:5432
    networks:
      - backend-network
    volumes:
      - ./db/01-create-database.sql:/docker-entrypoint-initdb.d/01-create-database.sql
      - ./db/02-create-tables.sql:/docker-entrypoint-initdb.d/02-create-tables.sql
      - ./db/03-populate.sql:/docker-entrypoint-initdb.d/03-populate.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
  backend:
    image: g0tn/soat-docker-challenge-backend
    environment:
      - DB_HOST=db # Will resolve to network internal IP
    networks:
      - backend-network
    ports:
      - 80:8080
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
networks:
  backend-network:
    